### ISSUE TITLE
Hostname Option not working?

### ISSUE THREAD

**Issue by darethehair** [erkstruwe/chromecast-cli#16]
In the command line parameters for this utility:

`-H, --host <host>            IP address or hostname of Chromecast (required)`

Hardcoding the IP address works just fine, but I am unable to get the 'hostname' option to work for me:

1) IP address method works great:

```
darren@penguin:~$ /usr/local/bin/chromecast --host 192.168.4.35  play http://192.168.5.45:8000/test.mp3
Playing http://192.168.5.45:8000/test.mp3
Status IDLE
```

2) Hostname option does not work -- is it expecting the name of the Chromecast device?

```
darren@penguin:~$ /usr/local/bin/chromecast --host "Downstairs Speaker" play http://192.168.5.45:8000/test.mp3
Client error Error: getaddrinfo ENOTFOUND Downstairs Speaker
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:107:26) {
  errno: -3008,
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'Downstairs Speaker'
}
```

Using another utility to show the addresses/names of my Chromecast devices:

```
darren@penguin:~$ catt scan
Scanning Chromecasts...
192.168.4.34 - Downstairs Google TV - Google Inc. Chromecast
192.168.4.35 - Downstairs Speaker - Google Inc. Google Home Mini
192.168.4.74 - Downstairs TV - KaonMedia KSTB2100
192.168.4.26 - Kitchen Speaker - Google Inc. Google Home Mini
192.168.4.73 - Kitchen TV - KaonMedia KSTB2100
```

Am I misunderstanding how this is intended to function?  Thanks!

**Comment by erkstruwe** [comment]
Hi!

By hostname, a DNS host name is meant. E. g. www.google.com is the hostname for a certain IP address. In a LAN, hostnames can exist, too. It has nothing to do with the Chromecast's "name".

**Comment by darethehair** [comment]
In that case, is it possible to add a feature (similar to other Chromecast CLI utilities) to target a Chromecast with its assigned name, rather than its current IP address?  This would protect the command from occasional re-assignments by the router.

**Comment by erkstruwe** [comment]
Hi! Unfortunately, that is not in the scope of this package. However, as for as I know, it is in `catt`'s scope that you referenced here. With that package, you can select a device by name. Alternatively, you can define a static IP address to be assigned in the DHCP server's (router's) settings.

**Comment by darethehair** [comment]
The 'catt' utility works well on its own, but it does not work for me in the ChromeOS 'crostini' environment -- but your 'chromecast' utility works great -- hence my query.
