### ISSUE TITLE
Crashes on Linux due to Windows line breaks

### ISSUE THREAD

**Issue by arturmaj** [erkstruwe/chromecast-cli#2]
Ubuntu 16.04 x86
When I run:
chromecast --host 192.168.1.100 status
I am getting:
/usr/bin/env: ‘node\r’: No such file or directory

**Comment by arturmaj** [comment]
The files are formatted in windows. The solution is conversion to UNIX.
> brew install dos2unix
> find /usr/local/lib/node_modules/chromecast-cli -name "*.js" | xargs sudo dos2unix

**Comment by erkstruwe** [comment]
Thanks for reporting. Will change it anyway.
