### ISSUE TITLE
YouTube playback

### ISSUE THREAD

**Issue by fregante** [erkstruwe/chromecast-cli#4]
Thanks for this! I found a way to play YouTube videos as well, using `youtube-dl` to get the raw URL:

```
chromecast-cli -f bestaudio --host $IP play (youtube-dl --get-url 'https://www.youtube.com/watch?v=WI4-HUn8dFc')
```

I thought some might find it useful. I use `-f bestaudio` because I my cast device is audio only

**Comment by erkstruwe** [comment]
Thanks. Added to README.md.
