### ISSUE TITLE
Stream to multiple devices

### ISSUE THREAD

**Issue by vespino** [erkstruwe/chromecast-cli#6]
First of all, great work on this project, works right away without issues. What I was wondering: I have multiple Nest Audio speakers around my house. I have been able to have them stream the same url, but these are not synchronized. I was wondering if it's possible to stream to the speaker group instead of each speaker individually.

**Comment by erkstruwe** [comment]
Hi vespino,
it's actually currently possible, but only if you know the group master's ip address and port. Unfortunately, they tend to change everytime a new group master is selected.
I found a small script that shows how to discover devices using mDNS. You can find it here: https://github.com/thibauts/node-castv2-client/wiki/How-to-discover-&-update-audio-groups. I'm sorry I don't have the time to implement that into chromecast-cli currently.

**Comment by vespino** [comment]
I guess a network sniffer would also be able to find this information?
