### ISSUE TITLE
Got a black screen with blue cast logo instead of Video

### ISSUE THREAD

**Issue by hourlier96** [erkstruwe/chromecast-cli#7]
Hi,

I tried to cast a simple video from my local by doing:

```code
chromecast --host 192.168.0.48 play ./myvideo.mp4
```

However the only thing displayed is a black screen with a blue cast logo. (The one you have when a video is finish)

here is the status of my Chromecast
![image](https://user-images.githubusercontent.com/45850718/100347245-5d0bc200-2fe5-11eb-8247-7cfb4586e2e8.png)

And the output of play
![image](https://user-images.githubusercontent.com/45850718/100347280-67c65700-2fe5-11eb-9f81-4c69efaed363.png)

I tried to cast with another CL tool (catt) and it works fine.

Is there anything i missed?

Working on Windows

Thanks

**Comment by erkstruwe** [comment]
Hi hourlier96,
thanks for your message. What `catt` does here, I assume, is it sets up an ad-hoc media server to serve your local file to the Chromecast device via network. `chromecast-cli` does not have such a functionality and can only trigger playback of sources that are already available via network (be it on the internet or local network).
